name: flame_playground
description: A game using Flame inside a Flutter app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  tiled: ^0.10.1
  flutter_svg: ^2.0.8
  flame: ^1.10.0
  flame_audio: ^2.1.2
  flame_forge2d: ^0.15.1
  flame_svg: ^1.8.4
  flame_tiled: ^1.15.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Background/
    - assets/images/Terrain/
    - assets/images/HUD/
    - assets/images/Items/Fruits/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Traps/Saw/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Main Characters/Guy One/
    - assets/images/Main Characters/
    - assets/data/
    - assets/tiles/
